### ISSUE TITLE
Site won't load up 

### ISSUE THREAD

**Issue by flawsom** [ItzNesbroDev/netflyer#60]
The site doesn't load up even after waiting a while upon the buffering at the url 

![Screenshot_2024-03-07-16-34-06-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItzNesbroDev/netflyer/assets/64182228/b8c745e6-62bc-4a40-95b8-1118bd70e702)

**Comment by RolexAvanPereDilli** [comment]
![Screenshot_2024-03-07-16-42-34-831_com kiwibrowser browser](https://github.com/ItzNesbroDev/netflyer/assets/150610306/b4ee650b-e457-4320-ab53-1517ee6169c6)
Well it works for me try refreshing

**Comment by ItzNesbroDev** [comment]
![Screenshot_2024-03-07-16-42-34-831_com kiwibrowser browser](https://github.com/ItzNesbroDev/netflyer/assets/76590320/1ab98256-5c33-48fd-9081-12ffb7c4e40b)
Well it works for me, try refreshing

**Comment by flawsom** [comment]
umm is this proxied or ip banned by indian sim operators ?

**Comment by flawsom** [comment]
It keeps on spinnin' round  & round here

![Screenshot (19)](https://github.com/ItzNesbroDev/netflyer/assets/64182228/8ab8ccbc-5345-4d7c-9a22-d7166e740bc2)

**Comment by ItzNesbroDev** [comment]
Can you open developer options and show me the photo of console?

**Comment by flawsom** [comment]
here, seems like some issue with the tmdb api

![Uploading Screenshot (20).png…]()

**Comment by flawsom** [comment]
here, seems like some issue with the tmdb api

![Screenshot (20)](https://github.com/ItzNesbroDev/netflyer/assets/64182228/70505ead-66b7-4b7d-a23a-05d16fad9f3b)

**Comment by ItzNesbroDev** [comment]
So it's tmdb server's problem try refreshing the page so many time maybe it works, tho I will try to fix that if that is our codes problem

**Comment by ItzNesbroDev** [comment]
@flawsom Bro the website now i think the problem with tmdb has fixed

**Comment by flawsom** [comment]
@ItzNesbroDev nahh bro it's still the same

![Screenshot (22)](https://github.com/ItzNesbroDev/netflyer/assets/64182228/1d4b7204-58a5-4705-8107-317a4897b079)

**Comment by flawsom** [comment]
u can implement a proxy service on the site for thhis n, like cors proxy or something to render this through it

**Comment by ItzNesbroDev** [comment]
Well... I will look into that

**Comment by ItzNesbroDev** [comment]
@flawsom Does the issue fixed?

**Comment by flawsom** [comment]
It is still the same

**Comment by ItzNesbroDev** [comment]
maybe if you have an adblocker enabled can you disable and try it out?

**Comment by flawsom** [comment]
There's no ad blocker on chrome

**Comment by flawsom** [comment]
Idk if my ISP is blocking the IP routes of site or the server it's hosted upon

**Comment by ItzNesbroDev** [comment]
then can you try out using vpn for one time and tell me if it worked or not cuz only you have this issue soo far

**Comment by flawsom** [comment]
Yess, it loaded up as I used a vpn 
![Screenshot_2024-05-12-18-52-11-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItzNesbroDev/netflyer/assets/64182228/5d7408c8-97a1-4d74-bcdf-97f6ba0ed416)

So perhaps it's the same as we assumed

**Comment by ItzNesbroDev** [comment]
okey so can you tell me your country? maybe i can fix the problem using proxy or smthing

**Comment by flawsom** [comment]
Am from India actually
