### ISSUE TITLE
question

### ISSUE THREAD

**Issue by johnx234** [ItzNesbroDev/netflyer#66]
WHICH TAG DID YOU ADD IN GOOGLE TAG MANAGER?

**Comment by johnx234** [comment]
I FORK R REPO WHAT HAVE YOU ADD IN FIREBASE TO USE WATCHLIST FOR EXAMPLE WHIC HPRODUCT OF FIREBASE SHOULD I ADD TO RUN WATCHLIST LIKE FIREBASE DB OR STORAGE ETC ?

**Comment by johnx234** [comment]
![image](https://github.com/ItzNesbroDev/netflyer/assets/114826338/6051e627-b663-4b3f-b98f-41a9f7520955)
now its loading

**Comment by ItzNesbroDev** [comment]
alright

**Comment by johnx234** [comment]
> alright

just loading, still not working

**Comment by ItzNesbroDev** [comment]
> > alright
> 
> just loading, still not working

Check developer tools console

**Comment by johnx234** [comment]
> > > alright
> > 
> > 
> > just loading, still not working
> 
> Check developer tools console

![image](https://github.com/ItzNesbroDev/netflyer/assets/114826338/19ec436e-e388-4ce1-8a8d-7337c8d29340)

**Comment by ItzNesbroDev** [comment]
> > > > alright
> > > 
> > > 
> > > just loading, still not working
> > 
> > 
> > Check developer tools console
> 
> ![image](https://private-user-images.githubusercontent.com/114826338/323302758-19ec436e-e388-4ce1-8a8d-7337c8d29340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzE3NDYsIm5iZiI6MTcxMzM3MTQ0NiwicGF0aCI6Ii8xMTQ4MjYzMzgvMzIzMzAyNzU4LTE5ZWM0MzZlLWUzODgtNGNlMS04YThkLTczMzdjOGQyOTM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjMwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmE3MzM2OTYzZDVlMWQ1NWNmM2NjYWJhNDRmMmYxM2RkOGIyMzcyMzhjYjU5N2Q4ZTdhYTBhNjVmNzkxNzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zPZ96yc2qxJQdcErdDxT6u-Cf_xQgUiVH74yVy33qlQ)

Check if the firestore is enabled, and check if the .env variables is correct

**Comment by johnx234** [comment]
> > > > > alright
> > > > 
> > > > 
> > > > just loading, still not working
> > > 
> > > 
> > > Check developer tools console
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/114826338/323302758-19ec436e-e388-4ce1-8a8d-7337c8d29340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzE3NDYsIm5iZiI6MTcxMzM3MTQ0NiwicGF0aCI6Ii8xMTQ4MjYzMzgvMzIzMzAyNzU4LTE5ZWM0MzZlLWUzODgtNGNlMS04YThkLTczMzdjOGQyOTM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjMwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmE3MzM2OTYzZDVlMWQ1NWNmM2NjYWJhNDRmMmYxM2RkOGIyMzcyMzhjYjU5N2Q4ZTdhYTBhNjVmNzkxNzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zPZ96yc2qxJQdcErdDxT6u-Cf_xQgUiVH74yVy33qlQ)
> 
> Check if the firestore is enabled, and check if the .env variables is correct

it is enable and all vairable is correct

**Comment by johnx234** [comment]
bro now it is working i was creating it in production mode now when i try for test it working

**Comment by ItzNesbroDev** [comment]
Ok
